layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;

layout(std430, binding = 0) buffer OutputBuffer {
    float outputData[];
};

void main() {
    uint idx = 
        gl_GlobalInvocationID.x + 
        gl_GlobalInvocationID.y * gl_WorkGroupSize.x + 
        gl_GlobalInvocationID.z * gl_WorkGroupSize.x * gl_WorkGroupSize.y;

    // Just zero out each element
    outputData[idx] = 0.0;
}
